name: Changelog & release

runs:
  using: "composite"
  steps:
      #- name: Checkout
      #- uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: ls
        shell: bash
        run: ls
      - name: package
        shell: bash
        run: |
          if [[ ! -f package.json ]]; then
            {
                echo '{'
                echo '  "dependencies": {'
                echo '    "semantic-release": "^18.0.1",'
                echo '    "conventional-changelog-conventionalcommits": "latest"'
                echo '  },'
                echo '  "release": {'
                echo '    "preset": "conventionalcommits",'
                echo '    "presetConfig": {'
                echo '        "types": [{ "type": "feat", "section": "🚀 Features" }]'
                echo '     },'
                echo '    "plugins": ['
                echo '      "@semantic-release/commit-analyzer",'
                echo '      "@semantic-release/release-notes-generator",'
                echo '      "@semantic-release/github"'
                echo '    ]'
                echo '  }'
                echo '}'
            } >> package.json
          fi
      - name: ls
        shell: bash
        run: ls
      - name: NPM
        shell: bash
        run: npm i
      - name: Semantic Release
        shell: bash
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
