name: Changelog & release

runs:
  using: "composite"
  steps:
      - name: package
        shell: bash
        run: |
          if [[ ! -f package.json ]]; then
            {
                echo '{}'
            } >> package.json
          fi
      - name: releaserc
        shell: bash
        run: |
          if [[ ! -f .releaserc ]]; then
            {
                echo '{'
                echo '  "preset": "conventionalcommits",'
                echo '  "presetConfig": {'
                echo '      "types": ['
                echo '         { "type": "feat", "section": "🚀 Features" },'
                echo '         { "type": "fix", "section": "🐛 Bug Fixes" },'
                echo '         { "type": "chore", "section": "🧽 Chores" }'
                echo '   ]},'
                echo '  "plugins": ['
                echo '    "@semantic-release/commit-analyzer",'
                echo '    "@semantic-release/release-notes-generator",'
                echo '    "@semantic-release/github"'
                echo '  ]'
                echo '}'
            } >> .releaserc
          fi
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-semantic-cache
      - name: NPM
        shell: bash
        run: npm i semantic-release@18.0.1 conventional-changelog-conventionalcommits@4.6.1
      - name: Semantic Release
        shell: bash
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
