name: Changelog & release

runs:
  using: "composite"
  steps:
      #- name: Checkout
      #- uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: NPM
        shell: bash
        run: npm i
      - name: Semantic Release
        shell: bash
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
