name: Changelog & release

runs:
  using: "composite"
  steps:
      #- name: Checkout
      #- uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: package
        shell: bash
        run: |
          if [[ ! -f package.json ]]; then
            {
                echo '{}'
            } >> package.json
          fi
      - name: releaserc
        shell: bash
        run: |
          if [[ ! -f .releaserc ]]; then
            {
                echo '{'
                echo '  "preset": "conventionalcommits",'
                echo '  "presetConfig": {'
                echo '      "types": [{ "type": "feat", "section": "ðŸš€ Features" }]'
                echo '      "types": [{ "type": "fix", "section": "ðŸ› Bug Fixes" }]'
                echo '      "types": [{ "type": "chore", "section": "ðŸ§½ Chores" }]'
                echo '   },'
                echo '  "plugins": ['
                echo '    "@semantic-release/commit-analyzer",'
                echo '    "@semantic-release/release-notes-generator",'
                echo '    "@semantic-release/github"'
                echo '  ]'
                echo '}'
            } >> .releaserc
          fi
      - name: NPM
        shell: bash
        run: npm i semantic-release@18.0.1 conventional-changelog-conventionalcommits
      - name: Semantic Release
        shell: bash
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
